name: 'Build Number Generator'
description: 'Generate sequential build numbers for workflow runs'
inputs:
  token:
    description: 'GitHub Token to create and delete refs (GITHUB_TOKEN)'
    required: false # Not required when getting the stored build number for later jobs, only in the first jobs when it's generated
  prefix:
    description: 'Prefix for the build-number-<num> tag to make it unique if tracking multiple build numbers'
    required: false

runs:
  using: 'node16'
  main: 'src/main.js'

outputs:
  build_number:
    description: 'Generated build number'
